name: Caller workflow for E2E

on:
    workflow_dispatch

jobs:
    deploy:
      uses: ./.github/workflows/1-reusable-workflow.yml 
      with:
        target-directory: dummy_dir
    e2e-tests:
      uses: sudheerdreddy/github-actions-e2e/.github/workflows/e2e.yml

